name: routing
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  dashboard:
    path: ../dashboard
  keg_line:
    path: ../keg_line
  line_one:
    path: ../line_one
  line_two:
    path: ../line_two
  splash:
    path: ../splash
  flutter:
    sdk: flutter
  go_router: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  go_router_builder: ^4.1.1
    
flutter:
  uses-material-design: true
