name: database
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  sembast: ^3.8.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
