name: keg_line
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
